### ISSUE TITLE
seg fault when running benchmark run dec2006_heelis_gpi

### ISSUE THREAD

**Issue by mfleduc** [NCAR/tiegcm#20]
Hello! I am having an issue trying to run the dec2006_heelis_gpi benchmark run in an interactive job on derecho. I have followed the documentation to ensure that I have the proper modules, python packages, etc loaded in my conda environment. 

Upon running the command 

python $TIEGCMHOME/tiegcmrun/tiegcmrun.py -bench dec2006_heelis_gpi -c -e

I am prompted to use the command 

mpirun $TIEGCMHOME/exec/tiegcm.exe $TIEGCMHOME/stdout/dec2006_heelis_gpi_2.5x0.25.inp

consistent with the data directory that I have supplied though $TIEGCMDATA. I have attached the input file as well. This makes a copy of the source file in the /hist/ directory with a few other fields (corresponding to input files) and then the model segfaults.

 I have already tried setting ulimit -s unlimited as advised in other places and have not had any success. I have the same issue if I submit the decsol_smin job as a batch job. The .inp and output files are attached as well.

Has anyone else seen this issue? 

[dec2006_heelis_gpi_2.5x0.25.inp.txt](https://github.com/user-attachments/files/16789702/dec2006_heelis_gpi_2.5x0.25.inp.txt)
[error from tiegcm.txt](https://github.com/user-attachments/files/16789597/error.from.tiegcm.txt)
[decsol_smax_2.5x0.25.inp.txt](https://github.com/user-attachments/files/16789847/decsol_smax_2.5x0.25.inp.txt)
[decsol_smax.out.txt](https://github.com/user-attachments/files/16789848/decsol_smax.out.txt)

**Comment by hzfywhn** [comment]
I notice that you are using a different data directory than we hosted. Can you try /glade/campaign/hao/itmodel/tiegcm3.0/data to see if it proceeds?

**Comment by mfleduc** [comment]
Thank you! The seg fault still occurs if I use data from that folder.

**Comment by hzfywhn** [comment]
Are you trying to do a REMIX driven TIEGCM run? If it is, please check if
the "msphere.mix.h5" is in the same folder as the TIEGCM executable. If
not, comment out the MIXFILE line in the input file.

**Comment by mfleduc** [comment]
The run still segfaults if I use the suggested directory and if I comment out the MIXFILE line in the input file. I do not have any file of that name anywhere, should it have been automatically generated?

**Comment by hzfywhn** [comment]
MIXFILE is an optional input. I actually successfully did a run based on
your input file, now I believe your failing run is due to the corrupted
source file. Please regenerate it using tiegcmrun based on
/glade/campaign/hao/itmodel/tiegcm3.0/data/2.5x0.25_z11/decsol_f70.nc

**Comment by AnonNick** [comment]
The MIXFILE seems to have a faulty default. I'll push a fix to not populate that parameter. 
You should be able to remove / comment out that line and do a run.
Thank you for figuring it out.

Due to a recent update the source files that were previously being used for TEIGCM are showing errors.
You should find the list of working SOURCE files here: `/glade/campaign/hao/itmodel/tiegcm3.0/data/2.5x0.25_z11/`
For benchmarks, if the benchmark name is *_smax use _f200.nc files if its *_smin use _f70.nc files.

Following benchmarks are working:
Seasons:
- decsol_smax
- decsol_smin
- junsol_smax
- junsol_smin
- mareqx_smax
- mareqx_smin
- sepeqx_smax
- sepeqx_smin


The following benchmarks are not available at the moment due to this issue.
Storms:
- dec2006_heelis_gpi
- dec2006_weimer_imf
- ul2000_heelis_gpi
- jul2000_weimer_imf
- nov2003_heelis_gpi
- nov2003_weimer_imf
- whi2008_heelis_gpi
- whi2008_weimer_imf

Climatology:
- climatology_smax
- climatology_smin


A fix for automatically suggesting SOURCE files to user is in the works in the dev_engage branch.

**Comment by mfleduc** [comment]
Thank you both very much! I will update when I have gotten everything to go correctly, although this probably won't be until Tuesday.
